#!/bin/sh

# Access config files
alias nvimrc='nvim ~/.config/nvim/'
alias bspwmrc='nvim ~/.config/bspwm/'
alias sxhkdrc='nvim ~/.config/sxhkd/'
alias polybarrc='nvim ~/.config/polybar/forest/'
alias tmuxrc='nvim ~/.config/tmux/'
alias nnnrc='nvim ~/.config/nnn/'
alias zshrc='nvim ~/.config/zsh/'

# Update zsh plugins
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colorize ls output
alias ls='ls --color=auto'

# Confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Easier to read disk (show MB etc.)
alias df='df -h'
alias free='free --mega -h'

# Mullvad VPN
alias mvc='mullvad connect -w'
alias mvd='mullvad disconnect -w'
alias mvs='mullvad status'

# Git
alias Gs="git status"
alias Gcm="git checkout main"
alias Gcd="git checkout dev"

