#! /bin/sh
bspc rule -r "*"

#Keyboard mappings/settings
setxkbmap -model pc104 -layout us,se -option grp:alt_shift_toggle
xset r rate 450 30

### Starting programs

#sxhkd: keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

#picom: compositor
killall -9 -qw picom 2>/dev/null; picom &

#feh: set wallpaper
~/.fehbg &

#polybar: status bar
bash ~/.config/polybar/launch.sh --forest &

#dropbox: file sharing
dropbox start &

### Settings

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6
bspc monitor DP-1    -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config automatic_scheme          alternate
bspc config split_ratio               0.50
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

### Rules

bspc rule -a Firefox-esr desktop='^4' follow=on
bspc rule -a Google-chrome desktop='^8' follow=on
bspc rule -a KeePassXC desktop='^7' follow=on
bspc rule -a Code desktop='^1' follow=on
bspc rule -a mpv state=fullscreen
