#! /bin/sh

#Reset all rules
bspc rule -r "*"

# Keyboard mappings/settings
setxkbmap -model pc104 -layout us,se -option grp:alt_shift_toggle
xset r rate 450 30

### Starting programs

#sxhkd: keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

#picom: compositor
killall -9 -qw picom 2>/dev/null; picom &

#feh: set wallpaper
~/.fehbg &

#polybar: status bar
bash ~/.config/polybar/launch.sh --forest &

#redshift: blue light filter
# BUG redshift.conf does not load, the command equivalent is used as a temporary fix.
killall redshift &
redshift -l 59.62:17.72 -t 6400:4500 -b 1.0:0.75 -m randr -P &

#dropbox: file sharing
dropbox start &

### Settings

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6
bspc monitor DP-1    -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config automatic_scheme          alternate
bspc config split_ratio               0.50
bspc config single_monocle            true
bspc config gapless_monocle           true
bspc config borderless_monocle        true
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

### Rules
# --one-shot: Only follow this rule once

bspc rule --add Firefox-esr --one-shot desktop='^4' follow=on
bspc rule --add Google-chrome --one-shot desktop='^8' follow=on
bspc rule --add Code --one-shot desktop='^1' follow=on
bspc rule --add KeePassXC --one-shot desktop='^7' follow=on
bspc rule --add mpv state=fullscreen
