#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Keyboard mappings/settings
setxkbmap -model pc104 -layout us,se -option grp:alt_shift_toggle
xset r rate 450 30

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6
bspc monitor DP-1    -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config automatic_scheme      alternate
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#feh: set wallpaper
~/.fehbg &

#dropbox: file sharing
dropbox start &

#picom: compositor
killall -9 -qw picom 2>/dev/null; picom &

